version = 0.1
[vandes16]
[vandes16.deploy]
[vandes16.deploy.parameters]
stack_name = "i8c-awsintegration-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4n7uhuyscjya"
s3_prefix = "i8c-awsintegration-demo"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MagnetoSystemIdentifier=\"Magneto-test-001\" MagnetoAccessToken=\"pkp0d6nx8vzejofq26yx7s8m972fe8rf\" MagnetoHostname=\"35.156.207.232\" MagnetoApiPageSize=\"5\" PollingPointerDynamoDbName=\"MagnetoPollingPointer\" MSTeamsWebhookUrl=\"https://cronos.webhook.office.com/webhookb2/6991badf-a59b-4834-a02c-392c8ccd775b@49c3d703-3579-47bf-a888-7c913fbdced9/IncomingWebhook/efe67ef287234dc4ad5eef007d191e5e/f326b0c8-0111-4e5b-b938-f04a00f85e82\" EventbusName=\"i8c-wickey-customers\" FollowupESUrl=\"https://search-i8c-wickey-monitoring-xeltrgw7sul2svhig44yo4jy2a.eu-central-1.es.amazonaws.com\" FollowupESUsername=\"vandes16\" FollowupESPassword=\"7anP3Cava08\""
