# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  i8c-awsintegration-demo

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

Parameters:

  MagnetoSystemIdentifier:
    Type: String
    Default: REPLACEME
  MagnetoAccessToken:
    Type: AWS::SSM::Parameter::Value<String>
    Default: MagnetoAccessToken
    Description: The instance name SSM parameter
  MagnetoHostname:
    Type: AWS::SSM::Parameter::Value<String>
    Default: MagnetoHostname
  MagnetoApiPageSize:
    Type: String
    Default: 5
  PollingPointerDynamoDbName:
    Type: String
    Default: REPLACEME
  MSTeamsWebhookUrl:
    Type: String
    Default: REPLACEME
  EventbusName:
    Type: String
    Default: i8c-wickey-orders
  FollowupESUrl:
    Type: String
    Default: REPLACEME
  FollowupESUsername:
    Type: String
    Default: REPLACEME
  FollowupESPassword:
    Type: String
    Default: REPLACEME

Globals:
  Function:
    Layers:
    - !Ref FunctionLayer
    - !Ref DependencyLayer
    Runtime: nodejs14.x
    Timeout: 100
    Tracing: Active
    MemorySize: 256
    Environment:
        Variables:
          FollowupESUrl: !Ref FollowupESUrl
          FollowupESUsername: !Ref FollowupESUsername
          FollowupESPassword: !Ref FollowupESPassword

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # This is an SQS queue with all default configuration properties. To learn more about the available options, see
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html
  SimpleQueue:
    Type: AWS::SQS::Queue
  # This is the Lambda function definition associated with the source code: sqs-payload-logger.js. For all available properties, see
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  SQSPayloadLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that logs the payload of messages sent to an associated SQS queue.
      Runtime: nodejs14.x
      Handler: src/handlers/sqs-payload-logger.sqsPayloadLoggerHandler
      # This property associates this Lambda function with the SQS queue defined above, so that whenever the queue
      # receives a message, the Lambda function is invoked
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SimpleQueue.Arn
      MemorySize: 128
      Timeout: 25 # Chosen to be less than the default SQS Visibility Timeout of 30 seconds
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  FnAdapterBolcomWebsitePoller:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bolcom-website-poller.lambdaHandler
      CodeUri: dist/adapters
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0/15 * * * ? *)
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - 'xray:PutTraceSegments'
              - 'xray:PutTelemetryRecords'
            Resource:
              - '*'
      Environment:
        Variables:
          MagnetoAccessToken: !Ref MagnetoAccessToken
          MagnetoHostname: !Ref MagnetoHostname
          MagnetoHostname2: '{{resolve:ssm-secure:MagnetoAccessToken'
          MagnetoHostname3: '{{resolve:ssm:MagnetoHostname'
          MagnetoHostname4: '{{resolve:ssm-secure:MagnetoAccessToken:1'
          MagnetoHostname5: '{{resolve:ssm:MagnetoHostname:1'

  FnBolAdapterTypescript2kak:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ada-test.lambdaHandler
      CodeUri: dist/adapters
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0/15 * * * ? *)
      Policies:
          - Statement:
            - Effect: Allow
              Action:
                - 'xray:PutTraceSegments'
                - 'xray:PutTelemetryRecords'
              Resource:
                - '*'
  FunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: FunctionLayer
      ContentUri: src/layers/
      CompatibleRuntimes:
      - nodejs14.x
      RetentionPolicy: Retain
  DependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: dependency-layer
      ContentUri: src/dependencies/
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Retain