AWSTemplateFormatVersion: 2010-09-09
Description: i8c-awsintegration-demo
Transform:
- AWS::Serverless-2016-10-31
Parameters:
  MagnetoSystemIdentifier:
    Type: String
    Default: REPLACEME
  MagnetoAccessToken:
    Type: String
    Default: REPLACEME
  MagnetoHostname:
    Type: String
    Default: REPLACEME
  MagnetoApiPageSize:
    Type: String
    Default: 5
  PollingPointerDynamoDbName:
    Type: String
    Default: REPLACEME
  MSTeamsWebhookUrl:
    Type: String
    Default: REPLACEME
  EventbusName:
    Type: String
    Default: i8c-wickey-orders
  FollowupESUrl:
    Type: String
    Default: REPLACEME
  FollowupESUsername:
    Type: String
    Default: REPLACEME
  FollowupESPassword:
    Type: String
    Default: REPLACEME
Globals:
  Function:
    Layers:
    - Ref: FunctionLayer
    - Ref: DependencyLayer
    Runtime: nodejs14.x
    Timeout: 100
    Tracing: Active
    MemorySize: 256
    Environment:
      Variables:
        FollowupESUrl:
          Ref: FollowupESUrl
        FollowupESUsername:
          Ref: FollowupESUsername
        FollowupESPassword:
          Ref: FollowupESPassword
Resources:
  SimpleQueue:
    Type: AWS::SQS::Queue
  SQSPayloadLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that logs the payload of messages sent to an
        associated SQS queue.
      Runtime: nodejs14.x
      Handler: src/handlers/sqs-payload-logger.sqsPayloadLoggerHandler
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: Fn::GetAtt SimpleQueue.Arn
      MemorySize: 128
      Timeout: 25
      Policies:
      - AWSLambdaBasicExecutionRole
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-4n7uhuyscjya/3f0e890a8e4fa4636a7d511aaa515aea
  FnAdapterBolcomWebsitePoller:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bolcom-website-poller.lambdaHandler
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-4n7uhuyscjya/a54d0d712121d76cafa61e73f8fe6dde
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0/15 * * * ? *)
      Policies:
      - Statement:
        - Effect: Allow
          Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
          Resource:
          - '*'
  FnBolAdapterTypescript2kak:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ada-test.lambdaHandler
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-4n7uhuyscjya/a54d0d712121d76cafa61e73f8fe6dde
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0/15 * * * ? *)
      Policies:
      - Statement:
        - Effect: Allow
          Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
          Resource:
          - '*'
  FunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: FunctionLayer
      ContentUri: s3://aws-sam-cli-managed-default-samclisourcebucket-4n7uhuyscjya/619904245b6c093e63686d132a15418d
      CompatibleRuntimes:
      - nodejs14.x
      RetentionPolicy: Retain
  DependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: dependency-layer
      ContentUri: s3://aws-sam-cli-managed-default-samclisourcebucket-4n7uhuyscjya/208861c3e749ccf70f634ce1e70e4352
      CompatibleRuntimes:
      - nodejs14.x
      RetentionPolicy: Retain
